Nab 458 samples client management ja
Fintan-contents/nablarch-system-development-guide pull request #100
Opened 2022-09-21 09:13 UTC by ando-mitsuhiro

サンプルプロジェクト：顧客管理システムの日本語版修正対応

2022-09-27 06:47 UTC, kumagoro1202 requested changes

2022-09-27 06:47 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/main/java/com/nablarch/example/climan/common/jaxrs/ClimanJackson2BodyConverter.java
>          super.configure(objectMapper);
スネークケースで書き込む設定をなくしてしまうとこのクラス自体の存在意義がないように見えます。
このクラス自体削除した方がすっきりするのではないでしょうか。

2022-09-27 06:47 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +        support.assertStatusCode(register, HttpResponse.Status.OK, registerResponse);
ステータスが設計書から乖離してしまっています。

2022-09-27 06:47 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +                //.assertThat("$.clientId", is(not(null)), register + "[顧客ID]")
コメントアウトしているのはなぜですか？

2022-09-27 06:47 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/main/java/com/nablarch/example/climan/rest/client/ClientService.java
> +        return result.get(0);
client_nameにはユニークキー制約がついているのでfindAllBySqlFileではなくfindBySqlFileを使うべきではないでしょうか。

2022-09-27 06:47 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
> +        assertNotNull(result);
resultがnotNullであることではなくclientとresultがequalであることをassertするべきではないでしょうか。

2022-09-27 06:47 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/common/web/ClimanJacksonBodyConverter.java
>      }
スネークケースの設定をなくしたことで継承元のJacksonBodyConverterとまったく同じものになっています。このクラスは不要ではないでしょうか。

2022-09-27 11:41 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/main/java/com/nablarch/example/climan/rest/client/ClientService.java
> +        return result.get(0);
メソッドを変更しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/62d55e2f86d38bbf3a30ec22d1170d8942c1dab7
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/31966704299ab17d098dbaa24d83a735c926c02d

2022-09-27 11:48 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +                //.assertThat("$.clientId", is(not(null)), register + "[顧客ID]")
clientIdが自動採番されるため、clientIdの検証は消しています。
コメントアウト個所は削除しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/1e68264787b0b80fbebbc377ab965e26871c7354

2022-09-27 11:50 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
> +        assertNotNull(result);
テストコードを修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/af23809ae68e1cdfe73a4164317fba0d0abb5603

2022-09-27 11:51 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/common/web/ClimanJacksonBodyConverter.java
>      }
不要になったため削除しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/f93c92f864ae8c68bf2ce77093a98b6f46524ac5

2022-09-27 11:52 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +        support.assertStatusCode(register, HttpResponse.Status.OK, registerResponse);
設計に合わせて実装を変更しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/f8d58545b420ffa98bd0cc0f3a9695bad025acb1
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/ed55d67be6679e48e06ed37cac9601424eef8afd

2022-09-27 11:54 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/main/java/com/nablarch/example/climan/common/jaxrs/ClimanJackson2BodyConverter.java
>          super.configure(objectMapper);
write処理は必要になったためwriteのみ残して不要部分を削除しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/37cfdf9c725575334562a288122a4b915c2cbf97

2022-09-28 00:19 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/main/java/com/nablarch/example/climan/common/jaxrs/ClimanJackson2BodyConverter.java
>          super.configure(objectMapper);
writeも要らないと思います。また非公開APIを使用した実装になっているので公開APIを使うようにするべきです。

https://github.com/Fintan-contents/nablarch-system-development-guide/pull/107/commits/5dbb41f9c3911f91b9d20e18575fe54b4e24ab72

2022-09-28 00:30 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +        support.assertStatusCode(register, HttpResponse.Status.OK, registerResponse);
BodyConverterはActionで使用するものではないです。[RFC7231](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.3)でリソースの作成に成功したら201を返すのはSHOULDになっていてMUSTではないので無理やり201を返すようにするより設計を変更して200を返すにしたほうがいいです。

2022-09-28 00:31 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +                //.assertThat("$.clientId", is(not(null)), register + "[顧客ID]")
自動採番されたclientIdが返ってくることは検証するべきです。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/107/commits/25faa14a6c0bcf1e3545413c87e0a04acc6aeb97

2022-09-28 00:32 UTC, kumagoro1202 commented
修正案を#107のPRにしました。

2022-09-29 02:43 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +                //.assertThat("$.clientId", is(not(null)), register + "[顧客ID]")
設計を変更し、レスポンス生成方法を変更しました。

https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/7fc7f5f2c323f46b91494bc6278b52996ab0d42e
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/04843541dfc74ac1cf523bd8a9930932ea0b28d2

2022-09-29 02:45 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +        support.assertStatusCode(register, HttpResponse.Status.OK, registerResponse);
設計を変更し、レスポンス生成方法を変更しました。

https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/7fc7f5f2c323f46b91494bc6278b52996ab0d42e

2022-09-29 02:46 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/main/java/com/nablarch/example/climan/common/jaxrs/ClimanJackson2BodyConverter.java
>          super.configure(objectMapper);
設計変更し、クラスを廃止しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/100/commits/4627f8d6c441a88d01d53c57bf2ccfe1b1542ff6

2022-09-29 09:16 UTC, kumagoro1202 approved these changes

2022-09-29 09:16 UTC, merged