修正箇所対応漏れの対応
Fintan-contents/nablarch-system-development-guide pull request #116
Opened 2022-10-05 08:24 UTC by ando-mitsuhiro

2022-10-05 11:04 UTC, kumagoro1202 requested changes

2022-10-06 02:02 UTC, ando-mitsuhiro commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/PGUT工程/pg/コーディングに関する命名規約.md
> +| 共通機能画面     | 処理を表す単語 + .jsp                  | menu.jsp, topPage.jsp    |
指摘通り見直しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/116/commits/f3d8c16e72223a7df205d06a1f01ed4940c40821

2022-10-06 02:03 UTC, ando-mitsuhiro commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/PGUT工程/pg/コーディングに関する命名規約.md
> +| エラー画面       | エラー内容表す単語 + .jsp              | PERMISSION-ERROR.jsp     |
上記配置場所の命名側の修正に統合しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/116/commits/f3d8c16e72223a7df205d06a1f01ed4940c40821

2022-10-06 02:04 UTC, ando-mitsuhiro commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/要件定義工程/画面モックアップ作成ガイド.md
> +共通機能をまとめたcommonや、エラーページを配置するerrorPagesもそれぞれ作成して分類して配置します。
指摘通り修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/116/commits/d3e6bbc75a93d2769ae1f80eee010d97955e8ec1

2022-10-06 04:06 UTC, kumagoro1202 requested changes

2022-10-06 04:06 UTC, kumagoro1202 commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/README.md
> +    - [設計（共通）](#設計（共通）)
口頭で伝えた通りツールを使って目次を作ってください。

VSCodeのMarkdown All in Oneなど

2022-10-06 06:02 UTC, ando-mitsuhiro commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/README.md
> +    - [設計（共通）](#設計（共通）)
メニューを再作成しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/116/commits/f517767304d1310caea91aeb0dbf39310616457c

2022-10-06 07:47 UTC, merged