Junit test追加
Fintan-contents/nablarch-system-development-guide pull request #122
Opened 2022-10-18 04:08 UTC by ando-mitsuhiro

2022-10-18 06:18 UTC, kumagoro1202 requested changes

2022-10-18 06:18 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +class ProjectSearchFormTest extends FormTestSupport<ProjectSearchForm> {
クラス内のテストの順序とテスト仕様書のテストの順序を同じにしてください。（レビュー負荷低減のため）

2022-10-18 06:18 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +        form.setProjectStartDateTo("2022/01/31");
テスト仕様書では

> 開始日_TOが開始日_FROMの一日後

となっています。

2022-10-18 06:18 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +        form.setProjectEndDateTo("2022/01/31");
テスト仕様書では

> 終了日_TOが終了日_FROMの一日後

となっています。

2022-10-18 06:18 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +        form.setProjectStartDateTo("2022/01/01");
テスト仕様書では

> 開始日_TOが開始日_FROMの一日前

となっています。

2022-10-18 06:18 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +        form.setProjectEndDateTo("2022/01/01");
テスト仕様書では

> 終了日_TOが終了日_FROMの一日前

となっています。

2022-10-18 06:18 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectUpdateFormTest.java
> +    }
（テスト仕様書に関する指摘）
テスト仕様書上でテストコードに記載のメソッド名が逆転しています。

2022-10-18 06:18 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectServiceTest.java
> +            }
それぞれのメソッドに適切な値が渡されることを確認してください。
今のテストだとperに渡すものとpageに渡すものが逆転していたり、関係ない数値が渡されていてもエラーになりません。

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectServiceTest.java
> +            }
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/239bddf8b525435a9337ee0f88a658bccc558f3b

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectUpdateFormTest.java
> +    }
修正してアップロードしなおしました。

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +        form.setProjectEndDateTo("2022/01/01");
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/a0bcfc177f3a21fb71d84ee436d0756891efb71a

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +        form.setProjectStartDateTo("2022/01/01");
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/a0bcfc177f3a21fb71d84ee436d0756891efb71a

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +        form.setProjectEndDateTo("2022/01/31");
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/a0bcfc177f3a21fb71d84ee436d0756891efb71a

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +        form.setProjectStartDateTo("2022/01/31");
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/a0bcfc177f3a21fb71d84ee436d0756891efb71a

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectSearchFormTest.java
> +class ProjectSearchFormTest extends FormTestSupport<ProjectSearchForm> {
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/a0bcfc177f3a21fb71d84ee436d0756891efb71a

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/test/FormTestSupport.java
> +public class FormTestSupport<T> {
修正し不要クラスを廃止しました。

https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/a003936222f8c0de41e1e6faae1efd8ef92ba87f
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/40a8ad28c713d4fc044f364c706f88d4820cbf54
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/a0bcfc177f3a21fb71d84ee436d0756891efb71a
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/0266fa7246fe5e127f5b1650a0a8cee844c078a4

2022-10-18 10:33 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/proman-project/proman-web/src/test/java/com/nablarch/example/proman/web/project/ProjectCreateFormTest.java
> +import static org.junit.Assert.*;
変更しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/40a8ad28c713d4fc044f364c706f88d4820cbf54

2022-10-20 10:35 UTC, kumagoro1202 commented
バッチの単体テスト仕様書が破損してしまっているようです。開くと「'単体テスト仕様書_リクエスト・取引単体(バッチ)_BA10601_期間内プロジェクト一覧出力バッチ.xlsx'の一部の内容に問題が見つかりました。～」というメッセージが表示されます。安藤さん環境では起きないですか？

2022-10-20 11:11 UTC, kumagoro1202 commented
ExportProjectsInPeriodActionRequestTest.xlsxで115行目にコマンド書いてくれてますが右側切れてるのでH列まで黒く網掛けしてもらえますか。

2022-10-24 10:49 UTC, kumagoro1202 requested changes
ClientActionTestのtestFindUnderUpperLimit、testInvalidClientFormは対応するテストケースがないので削除してください。

2022-10-24 10:49 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testFindCodeAndName1000() throws JSONException {
不要なJSONExceptionがついています。

2022-10-24 10:49 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testFindIndustryCodeAndClientNameNoClients() {
テストデータのシート名が「testFindIndustryCodeAndClientNa」と文字数制限で途切れていて読み込まれていません。このメソッド専用のデータは要らないはずなのでシート削除してください。

2022-10-24 10:49 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
> +    void testFindClientByIdForNoDataException() {
"For"NoDataExceptionは違和感あるのでtestFindClientByIdThrowsNoDataExceptionとかにしましょうか。

2022-10-24 10:49 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +
testInvalidClientGetFormとtestInvalidClientGetForm2はやってること同じなので一つでいいと思います。テストケースで`aaa`指定と`test`指定のパターンがあるから分けたのであればテストケースを修正して同じパラメータにしてください。

2022-10-24 10:49 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +        HttpResponse response = support.sendRequest(support.get(PATH + "/test"));
B10102_リクエスト単体テストNo.105-2-2、108-1-2はテスト仕様書の想定結果に「・メッセージ：不正なリクエストです。」とありますが、「・メッセージ：clientId:数値を入力してください。」が正しいはずなのでテスト仕様書修正してください。

2022-10-24 10:49 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testShowNoDataNotExistsClient() {
NoDataNotExistsと続くと初見では意味がわかりにくいので、上の`testShowNotExistsClient`と違いがわかるように`testShowWithEmptyClientTable`とかどうでしょう。

2022-10-24 10:49 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +        String clientName = RandomStringUtils.random(128, "１２３４５６７８９０");
見落としていてマージしてしまいましたが、`testRegisterClient`の中で`support.getBodyString(response)`の書き方を使っていますが、今回nablarch-testing-restは同時リリース対象じゃないので使えないです。他と同じように`response.getBodyString()`に戻してください。

2022-10-24 10:49 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testRegisterNoParameterClientName() {
テスト仕様書にこのパターンがありますが、観点としては「入力値に対してFormで完結するバリデーションが実行され、エラーがある場合はエラーとなること。」です。であればテスト仕様書のパラメータを変更して`testRegisterNoParameter`と統合してしまうのがいいと思います。これだけ個別にやる意味がないので。

2022-10-24 12:38 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
> +    }
テスト仕様書を修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 12:38 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
>       * 顧客検索で検索結果が上限件数を超える場合のテスト。
テスト仕様書を修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 12:39 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
> +                return Long.valueOf(SystemRepository.get("app.common.search.limit"));
全般的に指摘通り修正
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 12:39 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
>              }
指摘通り修正
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 12:39 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
> +        final Map<String, Boolean> invoked = new HashMap<String, Boolean>();
指摘通り修正
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 12:40 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +
統合して集約
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 12:40 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testShowNoDataNotExistsClient() {
メソッド名を見直して修正
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 12:41 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +        String clientName = RandomStringUtils.random(128, "１２３４５６７８９０");
指摘通り修正
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 12:41 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testRegisterNoParameterClientName() {
統合して集約
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/02100216b085f222bc387191c6703f4a3259047c

2022-10-24 13:12 UTC, kumagoro1202 requested changes

2022-10-24 13:12 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +
テスト仕様書にtestInvalidClientGetForm2の記載が残っています。

2022-10-24 13:12 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testRegisterNoParameterClientName() {
テスト仕様書に業種コードもパラメータなしとすることと、想定結果に業種コードのメッセージも入ることを追記してください。

2022-10-24 13:12 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testInvalidClientSearchForm() throws UnsupportedEncodingException {
これも登録同様テスト仕様書を修正して一つのテストにしましょう。

2022-10-24 13:14 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +
テスト仕様書にtestInvalidClientGetForm2の記載が残っています。

2022-10-24 13:15 UTC, kumagoro1202 commented
コンフリクトしてるのでdevelopをマージしてからクラス単体テストの結果入れるようにしてください。

2022-10-25 01:38 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
> +    /**
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/c6e41cca7cb82906ade9ca513cd4fabce9a46f20

2022-10-25 01:39 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientServiceTest.java
> +        Assertions.assertThrows(SearchResultUpperLimitException.class, () -> sut.findClient(new Client()));
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/c6e41cca7cb82906ade9ca513cd4fabce9a46f20

2022-10-25 01:40 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testInvalidClientSearchForm() throws UnsupportedEncodingException {
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/c6e41cca7cb82906ade9ca513cd4fabce9a46f20
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/262ba5449a0dbc27350d403fc6ecdbd4185e5668

2022-10-25 01:41 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testRegisterNoParameterClientName() {
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/9c838125b856b28f186c1650ac607f95b8c3c211

2022-10-25 01:41 UTC, ando-mitsuhiro commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +
修正しました。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/122/commits/45e28c39f906a74f6fa4d82d77fb25484db500df

2022-10-25 01:50 UTC, kumagoro1202 commented
単体テスト仕様書_リクエスト(Webサービス)_B10101_顧客検索.xlsx
B10101_リクエスト単体テスト
No.13-2-1
「以下のリクエストを送信する。
・「顧客名」：128文字以下の文字列」というテスト内容ですが、対応するテストコードはパラメータなしのリクエストになっています。

2022-10-25 01:53 UTC, kumagoro1202 commented
単体テスト仕様書_リクエスト(Webサービス)_B10101_顧客検索.xlsx
B10101_リクエスト単体テスト
No.18-2-1
テスト内容とテストコードが合っていません。

2022-10-25 01:57 UTC, kumagoro1202 commented on サンプルプロジェクト/ソースコード/climan-project/src/test/java/com/nablarch/example/climan/rest/client/ClientActionTest.java
> +    void testInvalidClientSearchForm() throws UnsupportedEncodingException {
テスト仕様書は直っていますが、testInvalidClientNameForSearchのテストメソッドが残っています。

2022-10-25 02:02 UTC, kumagoro1202 commented
単体テスト仕様書_リクエスト(Webサービス)_B10102_顧客詳細取得.xlsx
B10102_リクエスト単体テスト
No.105-2-2
想定結果欄のメッセージがおかしいです。2回同じメッセージが出力される想定結果になっている。

2022-10-25 02:15 UTC, kumagoro1202 commented
単体テスト仕様書_リクエスト(Webサービス)_B10103_顧客登録.xlsx
B10103_リクエスト単体テスト
104-1-2
105-2-1
108-1-1
108-2-1

テスト内容は空文字のパラメータとなっているが、対応するテストコードはパラメータなしのテストとなっている。
testRegisterNoParameterとは別にtestRegisterEmptyParameterみたいなテストメソッド作って空文字にした時の挙動をテストしてください。

2022-10-25 02:17 UTC, kumagoro1202 commented
ClientActionTestのtestInvalidClientNameForSearchとtestInvalidClientFormは対応するテスト仕様書がないので削除してください。

2022-10-25 02:18 UTC, kumagoro1202 commented
ClientActionTest.xlsx
使われないtestFindUnderUpperLimitシートがのこっています。

2022-10-25 05:08 UTC, kumagoro1202 commented
> 単体テスト仕様書_リクエスト(Webサービス)_B10101_顧客検索.xlsx B10101_リクエスト単体テスト No.18-2-1 テスト内容とテストコードが合っていません。

テストコード列とあわせてテストデータ列の修正が必要です。

2022-10-25 06:34 UTC, kumagoro1202 approved these changes

2022-10-25 06:35 UTC, merged