英語版のサンプルプロジェクトを日本語版に合わせて修正
Fintan-contents/nablarch-system-development-guide pull request #196
Opened 2024-07-19 13:06 UTC by tishijiri

英語版のサンプルプロジェクトを日本語版に合わせて修正しました。

- 英語版のサンプルプロジェクトを日本語版に合わせて修正
  - 主にはNablarch v6へのバージョンアップ
- 英語版の`proman-batch`がテスト失敗する状態だったので、テストデータを修正
- 日本語版のサンプルプロジェクトを参照している中で、一部修正が必要と判断した箇所を合わせて修正
  - Jenkinsで静的解析を実施した際の通知コメント
  - ソースコードのフォーマット（改行など）が正しくないもの
  - `dataSource`コンポーネントの`driverClassName`指定（プロパティで指定しているのに設定していない）

2024-07-22 12:16 UTC, kumagoro1202 requested changes

2024-07-22 12:16 UTC, kumagoro1202 commented on Sample_Project/Source_Code/proman-project/README.md
> +以下の3つのモジュールにより構成されます。
parentになっているproman-projectはモジュールとして記載しなくていいですかね？`mvn install`する対象なので書いても良い気がしました。

2024-07-22 12:16 UTC, kumagoro1202 commented on en/Sample_Project/Source_Code/climan-project/pom.xml
> +    <version.plugins.unpublished.api.checker>5-NEXT-SNAPSHOT</version.plugins.unpublished.api.checker>
ここは5-NEXT-SNAPSHOTなんですか？

2024-07-22 12:16 UTC, kumagoro1202 commented on en/Sample_Project/Source_Code/proman-project/proman-web/pom.xml
> +    <!-- コード管理 -->
これはミスですか？

2024-07-22 12:33 UTC, tishijiri commented on en/Sample_Project/Source_Code/proman-project/proman-web/pom.xml
> +    <!-- コード管理 -->
仰る通りミスです。修正しました。

0f472dcc094e39f93c452c8059cf92c200c8ed79

2024-07-22 12:36 UTC, tishijiri commented on en/Sample_Project/Source_Code/climan-project/pom.xml
> +    <version.plugins.unpublished.api.checker>5-NEXT-SNAPSHOT</version.plugins.unpublished.api.checker>
日本語版の話になりますが、アーキタイプの`v6-develop`が`5-NEXT-SNAPSHOT`を指定しているため、それに合わせる形としています。（[アーキタイプの該当箇所](https://github.com/nablarch/nablarch-single-module-archetype/blob/efaa0c0cfcdf47134973dd785584a272378a25e4/nablarch-archetype-parent/pom.xml#L74)）

[nablarch-unpublished-api-checker](https://github.com/nablarch/nablarch-unpublished-api-checker)は元々`v6-develop`も作成されていなかった（おそらくSpotBugsのプラグインでありNablarch v6には直接関係ないため）ので、アーキタイプの`v6-develop`も`develop`と変わらない指定となっています。

2024-07-22 12:40 UTC, tishijiri commented on Sample_Project/Source_Code/proman-project/README.md
> +以下の3つのモジュールにより構成されます。
元々書いていなかったけど改めて見ると書いてもいいんじゃないかという話であるとして。
Mavenのコンテキストだと「モジュール」は`<modules>`に指定しているプロジェクトを指すため、そこまで変ではないかなという気がしました（`install`するから書いておいた方がいいのではというのも、たしかに分かりやすくなる部分もあると思うところもあるのですが...）。

なので以前からの案内と同じくサブプロジェクトだけを列挙し、今回`proman-arch-test`を削除したため`4`→`3`へ変更する形でいいのではと思いました。

2024-07-22 12:58 UTC, kumagoro1202 commented on en/Sample_Project/Source_Code/climan-project/pom.xml
> +    <version.plugins.unpublished.api.checker>5-NEXT-SNAPSHOT</version.plugins.unpublished.api.checker>
> v6-developも作成されていなかった（おそらくSpotBugsのプラグインでありNablarch v6には直接関係ないため）

これはJakarta対応進めている途中でnablarch-unpublished-api-checkerが独立したモジュールとして切り出されたのでv6-develop作るスコープから漏れたのかもしれません。
バージョン管理考えた時に使用不許可APIチェックツールだけ5-NEXT-SNAPSHOTのままで行くかどうかは整理して検討したほうが良いと思いました。（この修正で考えることではないかも知れません。）

2024-07-23 01:59 UTC, kumagoro1202 approved these changes

2024-07-23 01:59 UTC, merged