開発標準にサンプルプロジェクト固有箇所を反映
Fintan-contents/nablarch-system-development-guide pull request #197
Opened 2024-07-23 02:44 UTC by tisuchida

https://github.com/nablarch-development-standards/nablarch-development-standards/tree/develop
のドキュメントに、サンプルプロジェクト固有の設計情報を反映する形でシステム開発ガイドの開発標準を修正しました。

Officeドキュメントへの修正で変更点を確認しづらいため、今回の変更内容を添付ファイルにまとめています。
[変更点.xlsx](https://github.com/user-attachments/files/16343074/default.xlsx)

2024-07-26 10:00 UTC, tisuchida commented
https://github.com/nablarch-development-standards/nablarch-development-standards/pull/43
に合わせて、単体テスト仕様書のフォーマットを統一しました。
直前のコミットからの変更内容は以下の通りです。

- 各単体テスト仕様書フォーマット
  - 「【テストターゲット名】クラス単体」シート名を「【リクエストID】クラス単体テスト」に変更
  - 「【リクエストID】リクエスト単体」シート名を「【リクエストID】リクエスト単体テスト」に変更
  - 「【リクエストID】リクエスト単体」シートのヘッダにある「リクエストID」「バッチ処理ID」を削除
  - 各シートのケースNoカラムヘッダに、サンプルの記載に合わせて採番方法のメモを追加

- 単体テスト仕様書(画面)_(取引ID)_(取引名).xlsx
  - 取引単体テストの排他制御エラーのテストケースNoを「5-2-2」から「5-3-1」に、その他エラーのテストケースNoを「5-2-3」から「5-4-1」に変更

- 実際の単体テスト仕様書
  - 「【テストターゲット名】クラス単体」シート名を「【リクエストID】クラス単体テスト」に変更
  - 「【リクエストID】リクエスト単体」シート名を「【リクエストID】リクエスト単体テスト」に変更
  - 「【リクエストID】リクエスト単体」シートのヘッダにある「リクエストID」「バッチ処理ID」を削除
  - 各シートのケースNoカラムヘッダに、サンプルの記載に合わせて採番方法のメモを追加

1be050b895853e5827a7776fc6350b75c6d7e2e5

2024-07-29 10:12 UTC, tisuchida commented
別途指摘を踏まえ、以下の通り修正しました。

- 各単体テスト仕様書フォーマット
  - 「【リクエストID】クラス単体テスト」シート名を「【テストターゲット名】クラス単体」に変更
  - 「【リクエストID】リクエスト単体テスト」シート名を「【リクエストID】リクエスト単体」に変更
  - 各リクエスト単体のシートヘッダの「テストターゲット名」の記載を削除し、代わりに「リクエストID」「バッチ処理ID」を追加

- 実際の単体テスト仕様書
  - 共通の修正
    - フォーマットでの修正事項を反映
    - クラス単体のシート名からリクエストIDを削除し、テストターゲット名を記載
  - 単体テスト仕様書(画面)_WA10101_認証
    - 「WA1010102_クラス単体」シートは削除（対応するクラスがないため）
    - 「WA1010101_クラス単体」シートを「LoginForm_クラス単体」シートに変更
  - 単体テスト仕様書(画面)_WA10201_プロジェクト登録
    - 「WA1020102_クラス単体」シートは削除（対応するクラスがないため）
    - 「WA1020103_クラス単体」シートは削除（対応するクラスがないため）
    - 「WA1020101_クラス単体」シートを「ProjectCreateForm_クラス単体」シートに変更
    - 「ProjectService_クラス単体」シートを作成
  - 単体テスト仕様書(画面)_WA10202_プロジェクト照会
    - 「WA1020201_クラス単体」シートを「ProjectSearchForm_クラス単体」シートに変更
    - 「ProjectService_クラス単体」シートを作成
    - 「ProjectDetailInitialForm_クラス単体」シートを作成
  - 単体テスト仕様書(画面)_WA10203_プロジェクト更新
    - 「WA1020302_クラス単体」シートは削除（対応するクラスがないため）
    - 「WA1020303_クラス単体」シートは削除（対応するクラスがないため）
    - 「WA1020301_クラス単体」シートを「ProjectUpdateForm_クラス単体」シートに変更
    - 「ProjectService_クラス単体」シートを作成
    - 「ProjectUpdateInitialForm_クラス単体」シートを作成
  - 単体テスト仕様書(画面)_WA10301_TOPメニュー
    - 「WA10301_クラス単体」シートは削除（対応するクラスがないため）
  - 単体テスト仕様書(バッチ)_BA10601_期間内プロジェクト一覧出力バッチ
    - 「BA1060101_クラス単体」シートは削除（対応するクラスがないため）
    - 設計書にあわせて、ドキュメント内の「期間内プロジェクト一括出力バッチ」の記載を「期間内プロジェクト一覧出力バッチ」に修正
  - 単体テスト仕様書(Webサービス)_B10101_顧客検索
    - 「B10101_クラス単体」シートを「ClientService_クラス単体」シートに変更
    - 「ClientSearchForm_クラス単体」シートを作成
  - 単体テスト仕様書(Webサービス)_B10102_顧客詳細取得
    - 「B10102_クラス単体」シートを「ClientService_クラス単体」シートに変更
    - 「ClientGetForm_クラス単体」シートを作成
  - 単体テスト仕様書(Webサービス)_B10103_顧客登録
    - 「B10103_クラス単体」シートを「ClientService_クラス単体」シートに変更
    - 「ClientForm_クラス単体」シートを作成

56dbda26bb86685fc25c68dd22ef50e6de594a08

2024-07-29 12:34 UTC, kumagoro1202 requested changes

2024-07-29 12:34 UTC, kumagoro1202 commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10101_認証.xlsx
WA1010102_リクエスト単体シートに以下の記載がありますが、WA1010102=ログアウト機能という読み替えが必要で所見で理解するのに一拍必要でした。

> ログアウト機能に適合する観点がないため、ログアウト機能は取引単体テストのみでテストを行う。

「ログアウト機能に」「ログアウト機能は」という記載は不要だと思います。

2024-07-29 12:34 UTC, kumagoro1202 commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10101_認証.xlsx
LoginForm_クラス単体シートに以下の記載がありますが、これも初見で何の話をしているの？となるので「クラス単体テストで確認が必要な観点なし。机上確認と取引単体テストで品質担保する。」などにして欲しいです。

> @AssertTrueによるバリデーションなど、クラス単体で確認が必要な処理なし

2024-07-29 12:34 UTC, kumagoro1202 commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10101_認証.xlsx
下の指摘とあわせて「リクエスト単体テストで確認が必要な観点なし。取引単体テストで品質担保する。」とかの方が良いか。ここで重要なのは確認観点がないことと、代替の品質担保をどこでするかということです。観点がない詳細な理由はテスト内容列に記載されているので、それをサマリ的に書く必要はないです。

2024-07-29 12:34 UTC, kumagoro1202 commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10101_認証.xlsx
取引単体シートの5-2-2、5-2-3はルールに則るなら5-3-1、5-4-1では？

2024-07-29 12:34 UTC, kumagoro1202 commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10101_認証.xlsx
取引単体だけ数式になってないのでクラス単体、リクエスト単体同様にルールを数式化してしまったほうが良いのでは？
（元々数式化したのは私ですが、取引単体を数式化しなかったのは明確な理由があるわけではなく数も少ないしええじゃろくらいの感覚なので、これだけ採番誤りが目立つなら数式化したほうが良いです。）

2024-07-29 12:34 UTC, kumagoro1202 commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10201_プロジェクト登録.xlsx
WA10101_認証と同様ですが、対象の観点がないシートに置いてくれているオブジェクトの文言に違和感があります。下手に各機能にあわせた書き方を検討するのではなく、WA10101_認証の指摘に書いたように確認が必要な観点がないことと代わりにテスト対象がどこでテストされるかだけを書いてもらった方が良いです。

2024-07-30 04:52 UTC, tisuchida commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(バッチ)_BA10601_期間内プロジェクト一覧出力バッチ.xlsx
採番ルールに合致するようケースNoを数式化しました。
フォーマット・実際のテスト仕様書いずれも、取引単体のケースNoを数式化しています。

2024-07-30 04:52 UTC, tisuchida commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10101_認証.xlsx
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/197#discussion_r1696301518
と同様に修正しました。

2024-07-30 05:00 UTC, tisuchida commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10101_認証.xlsx
オブジェクト文言を修正しました。
フォーマット・実際のテスト仕様書いずれも、実施しないテストシートのオブジェクト文言を修正しています。

2024-07-30 05:00 UTC, tisuchida commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10101_認証.xlsx
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/197#discussion_r1696307894
と同様に修正しました。

2024-07-30 05:00 UTC, tisuchida commented on Sample_Project/設計書/A1_プロジェクト管理システム/030_アプリ設計/110_テスト仕様書/単体テスト仕様書(画面)_WA10201_プロジェクト登録.xlsx
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/197#discussion_r1696307894
と同様に修正しました。

2024-07-31 02:30 UTC, tisuchida commented
別途指摘をふまえ、以下対応を実施しました。
- 成果物名に合わせ、「リクエスト一覧_A1_プロジェクト管理システム.xlsx」のファイル名を「URL一覧_A1_プロジェクト管理システム.xlsx」に変更
- 各単体テスト仕様書フォーマット
  - 「【リクエストID】_リクエスト単体」「【バッチ処理ID】_リクエスト単体」の各シート名を「【テストターゲット名】_リクエスト単体」に修正
  - リクエスト単体シートヘッダの「リクエストID」「バッチ処理ID」を「テストターゲット名」に修正
- 実際の単体テスト仕様書
  - フォーマットでの修正を反映
  - リクエスト単体シートヘッダの「テストターゲット名」には、システム機能設計書に記載されている画面ごとのIDを記載
  - リクエスト単体シートの5-4-1観点を、以下通り修正
    - （誤）「数値項目に有効範囲の下限値＋1が入力された場合、エラーとなること。」
    - （正）「数値項目に有効範囲の下限値－1が入力された場合、エラーとなること。」

2024-08-01 11:22 UTC, tisuchida commented
[開発標準での指摘](https://github.com/nablarch-development-standards/nablarch-development-standards/pull/43#discussion_r1699574009)を踏まえ、以下修正を実施しました。

単体テスト仕様書の修正
- シート名
  - バッチ・Webサービスについては、リクエスト単体のシート名を「【リクエストID】_リクエスト単体」に統一
  - 画面については、リクエスト単体のシート名を「【テストターゲット名】_リクエスト単体」に変更

- ヘッダフォーマット
  - いずれも、ヘッダの「テストターゲット名」の下に「リクエストID」を付与（開発標準に合わせた）
  - 画面のリクエスト単体ではリクエストIDが不要であるため、その旨メモに追記

- ヘッダの記載（実際の単体テスト仕様書）
  - バッチ・Webサービスについては、「テストターゲット名」「リクエストID」の記載を修正前に戻した
  - 画面については、「テストターゲット名」の記載を修正前（画面の日本語名）に戻し、画面IDを付与した
    - プロジェクト照会についてはテストターゲット名がもとより記載されていなかったため、設計書より画面名を記載

■URL一覧をリクエスト一覧に変更し、内部の記載も併せて「URL一覧」から「リクエスト一覧」に変更
■バッチのリクエスト一覧で、システム機能設計書の記載に合わせてリクエストID、リクエスト名、説明を修正

2024-08-07 00:36 UTC, tisuchida commented
別途指摘を踏まえ、以下修正しました（descriptionも併せて更新しています）。

■単体テスト仕様書(画面)\_(取引ID)\_(取引名)
-   「【リクエストID】\_リクエスト単体」シート
    -   「リクエストID」の記入欄に、以下の記載を追加（もともとメモとして記載していたのを、セルに記載）
        -   画面単位でリクエスト単体テストを実施するため、リクエストIDは不要。

2024-08-07 02:45 UTC, tisuchida commented
別途指摘を踏まえ、以下修正しました（descriptionも併せて更新しています）。

■UI標準(画面)別冊_UI部品カタログ
3.1.4. カレンダー日付入力
(3) 機能
(3-3) 読み取り専用(readonly)
- （変更前）readonly属性は設定不可。
- （変更後）readonly属性はサンプルプロジェクトにおいては設定しない。


5febd13f6acbb0e31d5bb6562550b1b80c2a75ce

2024-08-07 04:26 UTC, kumagoro1202 approved these changes

2024-08-07 04:27 UTC, merged