各READMEと要件定義工程の修正
Fintan-contents/nablarch-system-development-guide pull request #83
Opened 2022-08-09 05:45 UTC by opengl-8080

「サンプルプロジェクト開発ガイド」の下にある各 README.md と、要件定義工程の修正。

2022-08-09 23:43 UTC, kumagoro1202 requested changes

2022-08-09 23:43 UTC, kumagoro1202 commented on サンプルプロジェクト/README.md
> +- ただし、メンテナンス等の理由がある場合は、一部または全部の機能の提供を停止・再開（開閉局）できるものとする。
前の項と「ただし」が重複していて違和感があります。
「メンテナンスのための開閉局（一部または全機能の提供の停止・再開）はA社と合意することで可能とする。」とかどうでしょう。

2022-08-09 23:43 UTC, kumagoro1202 commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/README.md
> +  - [ユニットテストのJavaDocに関する規約](PGUT工程/ut/ユニットテストのJavaDocに関する規約.md)
プログラマー向け成果物セルフチェックリスト同様、NTFを使うバッチだけが対象かと思います。

2022-08-10 05:12 UTC, opengl-8080 commented on サンプルプロジェクト/README.md
> +- ただし、メンテナンス等の理由がある場合は、一部または全部の機能の提供を停止・再開（開閉局）できるものとする。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/83/commits/87879691e2d1837e93eb007833202706a729d17a

修正しました

2022-08-10 05:12 UTC, opengl-8080 commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/README.md
> +  - [ユニットテストのJavaDocに関する規約](PGUT工程/ut/ユニットテストのJavaDocに関する規約.md)
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/83/commits/2cbf4682d7970f75ee8aea70c9c14769546a6060

修正しました

2022-08-10 05:15 UTC, kumagoro1202 approved these changes

2022-08-10 05:15 UTC, merged