設計工程の修正
Fintan-contents/nablarch-system-development-guide pull request #87
Opened 2022-08-23 01:46 UTC by opengl-8080

`サンプルプロジェクト/サンプルプロジェクト開発ガイド` の設計工程の分の修正です。

2022-08-23 11:16 UTC, kumagoro1202 requested changes

2022-08-23 11:16 UTC, kumagoro1202 commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/設計工程/SQLファイル作成.md
> +SQLファイルの名前や配置場所、SQL IDの命名規約については[コーディング規約に関する命名規約](../PGUT工程/pg/コーディングに関する命名規約.md#SQLファイル)を参照してください。
SQLの書き方（Nablarchの特殊な構文）の情報への導線として解説書のリンクもつけるという話になっていたと思います。

2022-08-24 00:43 UTC, opengl-8080 commented on サンプルプロジェクト/サンプルプロジェクト開発ガイド/設計工程/SQLファイル作成.md
> +SQLファイルの名前や配置場所、SQL IDの命名規約については[コーディング規約に関する命名規約](../PGUT工程/pg/コーディングに関する命名規約.md#SQLファイル)を参照してください。
https://github.com/Fintan-contents/nablarch-system-development-guide/pull/87/commits/92ce9a45d15706c290cacb52b20b9aa0f12555dc

修正しました。

2022-08-24 00:46 UTC, kumagoro1202 approved these changes

2022-08-24 00:46 UTC, merged